apiVersion: v1
kind: Service
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  ports:
    - port: 80
  selector:
    app: myapp
    tier: frontend
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: myapp
        tier: frontend
    spec:
      containers:
      - image: cybernijntje/myapp:1.0
        name: myapp
        env:
        - name: MYAPP_DB_HOST
          value: myapp-mysql
        - name: MYAPP_DB_PASSWORD
          value: password
        ports:
        - containerPort: 80
          name: myapp
